name       : zsdx
version    : 1.12.2
release    : 4
source     :
    - https://gitlab.com/solarus-games/zsdx/-/archive/v1.12.2/zsdx-v1.12.2.tar.bz2 : a4d4cc9b41a4d52375e984f546cfe75736f604bc3ad194f6df1658ab6215c04f
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : games.rpg
summary    : Zelda - Mystery of Solarus DX - This quest is a free, open-source game that works with Solarus
description: |
    Zelda - Mystery of Solarus DX - This quest is a free, open-source game that works with Solarus
rundeps    :
    - solarus
setup      : |
    %cmake -DCMAKE_BUILD_TYPE=Release .
build      : |
    %make
install    : |
    %make_install
    for i in 16 24 32 48 64 128 256 512 1024; do \
        install -D -m 00644 data/logos/icon_$i.png $installdir/usr/share/icons/hicolor/"$i"x"$i"/apps/zsdx.png; \
    done
    install -D -m 00644 $pkgfiles/zsdx.desktop $installdir/usr/share/applications/zsdx.desktop
